#!/usr/bin/env groovy


pipeline {

    environment {
        WORKSPACE = "${pwd()}/cppBinary"
    }

    agent {
        dockerfile {
            filename "cppBinary/Dockerfile"
        }
    }

    stages {
        stage("Checkout") {
            steps {
                git credentialsId: 'git-ssh', url: 'git@gitlab.com:herychemo/QuickTestJenkinsFile.git'
            }
        }
        stage("Build") {
            steps {
                dir(WORKSPACE) {
                    sh """
                        rm -rf build 
                        mkdir build
                        cd build
                        cmake ..
                        make
                    """
                }
            }
        }
        stage("Run") {
            steps {
                dir(WORKSPACE) {
                    sh """
                        ./build/MainBinary
                        ./build/MainBinary World!
                        ./build/MainBinary bro
                    """
                }
            }
        }
        stage("Archive") {
            steps {
                archiveArtifacts artifacts: "cppBinary/build/MainBinary", onlyIfSuccessful: true
            }
        }
    }

}
