#!/usr/bin/env groovy

library identifier: 'custom-lib@master', retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'git@gitlab.com:herychemo/LabJenkinsSharedLibrary.git',
         credentialsId: 'git-ssh'])


pipeline {

    agent {
        docker { image 'node:7-alpine' }
    }

    stages {
        stage("Checkout") {
            steps {
                git credentialsId: 'git-ssh', url: 'git@gitlab.com:herychemo/QuickTestJenkinsFile.git'
            }
        }
        stage("Environment Validation") {
            steps {
                sh 'node --version'
                sh 'pwd'
                sh 'ls -l '
                sh 'hostname'
            }
        }
        stage("Run") {
            steps{
                sh """
                    node ./nodeScript/main.js
                """
            }
        }
        stage("Shared-lib-test") {
            steps {
                testStep 'something'
            }
        }
	}
}
